version: '2'
services:
  rabbit-1-server:
    image: ttsubo/rabbitmq:mitaka
    command: /bin/sh -c "/usr/local/bin/start-rabbitmq.sh"
    container_name: rabbit-1-server
    hostname: rabbit-1-server
    ports:
      - 15672:15672

  heat-engine:
    image: ttsubo/ubuntu:mitaka
    command: /bin/sh -c "sleep 15; python heat-engine.py --config-file conf/heat1.conf > /log/heat-1-engine.log 2>& 1"
    volumes:
    - ./log:/log
    container_name: heat-engine
    hostname: heat-engine

  heat-api:
    image: ttsubo/ubuntu:mitaka
    command: /bin/sh -c "sleep 30; python heat-api.py --config-file conf/heat1.conf > /log/heat-1-api.log 2>& 1"
    volumes:
    - ./log:/log
    container_name: heat-api
    hostname: heat-api

